<?php
namespace Application;

/**
 * Autogenerated controller class.
 * 
 * @package Application
 * @author Bedrock Framework Installer
 * @version 1.0.0
 * @created 08/21/2012
 * @updated 08/21/2012
 */
abstract class Control extends \Bedrock\Control {
	
}
?>