<?php
namespace Bedrock;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-24 at 18:20:27.
 */
class CommonTest extends \Bedrock\Common\TestCase {
	/**
	 * @var Common
	 */
	protected $_object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->_object = new Common;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Bedrock\Common::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Bedrock\Common::autoload
	 * @todo   Implement testAutoload().
	 */
	public function testAutoload() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Bedrock\Common::error
	 * @todo   Implement testError().
	 */
	public function testError() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
