<?php
namespace Application\Control;

/**
 * Autogenerated controller class.
 * 
 * @package Application
 * @author Bedrock Framework Installer
 * @version 1.0.0
 * @created 08/21/2012
 * @updated 08/21/2012
 */
class Index extends \Application\Control {
	/**
	 * The main index for the controller.
	 * 
	 * @param array $args an array of arguments passed from the GET string
	 * @return void
	 */
	public function index($args) {
		try {
			// Sample Output (feel free to delete this)
			$view = new \Application\View\Index();
			$view->setValue('message', 'Bedrock Framework Application: Installation Successful!');
			$view->render('test');




		}
		catch(\Exception $ex) {
			\Bedrock\Common\Logger::exception($ex);
		}
	}
}
?>